using NUnit.Framework;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
public class End : MonoBehaviour
{
    public GameObject gameOver;
    public Transform player;
    public Transform ai;
    public Transform finishLine;

    private List<string> finishOrder = new List<string>();
    public List<GameObject> raceCar = new List<GameObject>();

    public int totalCars;

    private void Start()
    {
        StartCoroutine(SetupRaceCars());
    }

    private IEnumerator SetupRaceCars()
    {
        yield return new WaitForEndOfFrame();

        if (raceCar.Count == 0)
        {
            GameObject[] cars = GameObject.FindGameObjectsWithTag("AI");
            raceCar.AddRange(cars);
        }

        raceCar.Add(CarSpawn.instance.owncar);


        totalCars = raceCar.Count;
    }

    


    private void OnTriggerEnter(Collider other)
    {
        GameObject gm = other.transform.root.gameObject;
        //Debug.Log("Car Trigger" + gm.name + " " + gameObject.name);

        if ((gm.CompareTag("AI") && !finishOrder.Contains(gm.name)) || (gm.CompareTag("Player") && !finishOrder.Contains(gm.name)))
        {
            finishOrder.Add(gm.name);
            int position = finishOrder.Count;

            if (gm.CompareTag("Player"))
            {
                PlayerPrefs.SetInt(Menu.LeaderboardRank, position - 1);
            }

            //Debug.Log("Car Trigger ++++++++++" + gm.name);
            if (gm.CompareTag("AI"))
            {
                EndcarMovement(gm.gameObject);
            }
            else
            {
                CarSpawn.instance.owncar.GetComponent<Controller>().MaxSpeed = 1;
            }

            if(position == totalCars)
            { 
                CoResult();
            }

        }
    }


   private void EndcarMovement(GameObject gm)
    {
        gm.GetComponent<AICarController>().enabled = false;
    }

    private void CoResult()
    {
        GameManager.Instance.ShowLevelComplete();
    }

    private bool gameEnded = false;

    // Optional UI text
    public Text resultText;

    void Update()
    {
        //if (gameEnded) return;

        //float playerDist = Vector3.Distance(player.position, finishLine.position);
        //float aiDist = Vector3.Distance(ai.position, finishLine.position);

        //// You can tweak this threshold as needed
        //float winThreshold = 1.0f;

        //if (playerDist < winThreshold)
        //{
        //    gameEnded = true;
        //    Win();
        //}
        //else if (aiDist < winThreshold)
        //{
        //    gameEnded = true;
        //    Lose();
        //}
    }

    void Win()
    {
        GameManager.Instance.ShowLevelComplete();
    }

    void Lose()
    {
        gameOver.SetActive(true);
    }

    void Restart()
    {
        SceneManager.LoadScene(SceneManager.GetActiveScene().name);
    }
}